name: instagram_clone
description: "Learning Responsive designing and Firebase cloudstore in flutter."
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  flutter_svg: ^1.0.0
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.3
  firebase_auth: ^5.3.1
  firebase_storage: ^12.3.2
  image_picker: ^1.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/ic_instagram (1).svg
