name: instagram_clone
description: "Learning Responsive designing and Firebase cloudstore in flutter."
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1
  firebase_storage: ^12.3.3
  image_picker: ^1.1.2
  provider: ^6.1.2
  uuid: ^4.5.1
  intl: ^0.19.0
  flutter_staggered_grid_view: ^0.6.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/ic_instagram.svg
